[Guysa_personal]
user = "guysa-AMG"
email = "moosathejoker@gmail.com"

[Guysa_student]
user = "gumumjhb025"
email = "gumumjhb025@student.wethinkcode.co.za"

[mbulelo]
user = "mbqabjhb025"
email = "mbqabjhb025@student.wethinkcode.co.za"

[Kwenzakele_Shongwe]
user = "Kwenzakele Shongwe"
email = "kwshojhb025@student.wethinkcode.co.za"

[Lindah_Mohalanyane]
user = "Lindah Mohalanyane"
email = "limohjhb025@student.wethinkcode.co.za"

[Botshelo]
user = "Botshelo"
email = "bomogjhb025@student.wethinkcode.co.za"

[Busisiwe]
user = "bumaljhb025"
email = "bumaljhb025@student.wethinkcode.co.za"

